=== MotoFanRu/ELFKIT_EP1_Linux/ELFKIT_EP1_Linux/bin/armperip.dtd
<!-- Copyright (c) ARM Limited 2000.  All Rights Reserved. -->
<!-- A document definition for ARM peripheral description files -->
<!-- Author: $Author: hbullman $ -->
<!-- Revision: $Revision: 1.3.4.3 $ -->
<!-- Date: $Date: 2002/04/26 14:05:02 $ -->

<!ELEMENT armperip (cvs_info?,
                    (displaytype | module | board | eice | processor | peripheral)*)>

<!ELEMENT cvs_info (author, revision, date)>
<!ELEMENT author (#PCDATA)*>
<!ELEMENT revision (#PCDATA)*>
<!ELEMENT date (#PCDATA)*>
<!ATTLIST revision
          min CDATA #IMPLIED
          max CDATA #IMPLIED>

<!ELEMENT displaytype (name, requires?, definition)>
<!ELEMENT name (#PCDATA)*>
<!ELEMENT requires (#PCDATA)*>
<!ELEMENT definition (#PCDATA)*>

<!ELEMENT module (type, register+)>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT register
   (name, bank?, description?,
      (memory+ | cpreg+ | cpreg2+ | cpmem+ | jtag+)?,
    attrib?, operation?, access, width, display?, revision?, dwarf?)>

<!ELEMENT description (#PCDATA)*>

<!ELEMENT memory EMPTY>
<!ATTLIST memory
          width    CDATA  "32"          
          base     CDATA  "0"
          offset   CDATA  "0"
          count    CDATA  "1">

<!ELEMENT cpreg EMPTY>
<!ATTLIST cpreg
          cp       CDATA  #REQUIRED
          crn      CDATA  #REQUIRED
          crm      CDATA  #REQUIRED
          opcode_1 CDATA  "0"
          opcode_2 CDATA  "0"
          car      CDATA  "">

<!ELEMENT cpreg2 EMPTY>
<!ATTLIST cpreg2
          cp       CDATA  #REQUIRED
          crn      CDATA  #REQUIRED
          crm      CDATA  #REQUIRED
          opcode_1 CDATA  "0"
          opcode_2 CDATA  "0"
          car      CDATA  "">

<!ELEMENT cpmem EMPTY>
<!ATTLIST cpmem
          cp       CDATA  #REQUIRED
          p        CDATA  #REQUIRED
          u        CDATA  #REQUIRED
          n        CDATA  "0"
          w        CDATA  #REQUIRED
          crd      CDATA  #REQUIRED
          car      CDATA  "">

<!ELEMENT jtag EMPTY>
<!ATTLIST jtag
          reg      CDATA  #REQUIRED>

<!ELEMENT revisions (#PCDATA)*>
<!ATTLIST revisions
          default CDATA "0">

<!ELEMENT bank (#PCDATA)*>
<!ELEMENT attrib (#PCDATA)*>
<!ELEMENT access (#PCDATA)*>
<!ATTLIST access
          mode     CDATA  "user">
<!ELEMENT width (#PCDATA)*>
<!ELEMENT operation (#PCDATA)*>
<!ELEMENT display (#PCDATA)*>

<!ELEMENT board (name, component+)>
<!ELEMENT peripheral (name, component+)>
<!ELEMENT eice (name, component+)>
<!ELEMENT component (name, type, base?)>
<!ELEMENT base (#PCDATA)*>
<!ELEMENT dwarf (#PCDATA)*>

<!ELEMENT processor (name, revisions?, core?, component*)>
<!ELEMENT core (#PCDATA)*>

<!ATTLIST displaytype version CDATA "0">
<!ATTLIST module version CDATA "0">
<!ATTLIST board version CDATA "0">
<!ATTLIST eice version CDATA "0">
<!ATTLIST processor version CDATA "0">
<!ATTLIST peripheral version CDATA "0">

<!-- EOF -->

=== MotoFanRu/ELFKIT_EP1_Linux/ELFKIT_EP1_Linux/bin/armboard.xml
<?xml version="1.0"?>
<!DOCTYPE armperip SYSTEM "armperip.dtd">
<!-- Copyright (c) ARM Limited 2000-2002. All Rights Reserved. -->

<!-- Definitions of ARM standard boards -->

<!--
The following references were used in the construction of this document:
[1] ARM Integrator/CM7TDMI User Guide, ARM DUI 0126A, ARM Ltd., 1999
[2] Integrator CM9x6ES Datasheet, CONGO-0021-CUST-DSHT-B02, ARM Ltd., 1999
[3] Integrator CM10200 Datasheet, CONGO-0022-CUST-DSHT-B, ARM Ltd., 2000
[4] ARM Integrator/AP User Guide, ARM DUI 0098A, ARM Ltd., 1999
[5] ARM Architecture Reference Manual, ARM DDI 0100E, ARM Ltd, 1996-2000
[6] ARM1020T (Rev 0) Technical Reference Manual, ARM DDI 0135A, ARM Ltd., 2001
[7] ARM1020E Technical Reference Manual, ARM DDI 0177A, ARM Ltd., 2001
[8] ARM922T (Rev 0) Technical Reference Manual, ARM DDI 0184B, ARM Ltd., 2001
-->

<armperip>

<cvs_info>
  <author>$Author: hbullman $</author>
  <revision>$Revision: 1.3.14.2 $</revision>
  <date>$Date: 2002/05/03 17:35:08 $</date>
</cvs_info>

<displaytype>
  <name>PCSR</name>
  <requires></requires>
  <definition>
TYPEDEF UnCS ENUM(WIDTH=3, DEFAULT="?")
{
        "IN"    =0,
        "EX"    =1
}

TYPEDEF PCSR_CT0CS ENUM(WIDTH=1, DEFAULT="?")
{
        "IN"    =0,
        "EX"    =1
}
  
TYPEDEF PCSR_CT1CS ENUM(WIDTH=1, DEFAULT="?")
{
        "IN"    =0,
        "EX"    =1
}

TYPEDEF PCSR_CT2CS ENUM(WIDTH=1, DEFAULT="?")
{
        "IN"    =0,
        "EX"    =1
}

TYPEDEF PCSR_LCDCE ENUM(WIDTH=1, DEFAULT="?")
{
        "IN"    =0,
        "EX"    =1
}

TYPEDEF PCSR_PWMCE ENUM(WIDTH=1, DEFAULT="?")
{
        "IN"    =0,
        "EX"    =1
}

TYPEDEF PCSR_SIRCE ENUM(WIDTH=1, DEFAULT="?")
{
        "IN"    =0,
        "EX"    =1
}

TYPEDEF PCSR(NAME="PCSR", CLASS="Board") COMPOSITE(WIDTH=9)
{
        SEPARATOR(TEXTNAME="UnCS-"),
        FIELD[2:0](NAME="CLK_SRC", TYPE=UnCS, ACCESS="R"),
        SEPARATOR(TEXTNAME=" T0-"),
        FIELD[3](NAME="TIMER0", TYPE=PCSR_CT0CS, ACCESS="R"),
        SEPARATOR(TEXTNAME=" T1-"),
        FIELD[4](NAME="TIMER1", TYPE=PCSR_CT1CS, ACCESS="R"),
        SEPARATOR(TEXTNAME=" T2-"),
        FIELD[5](NAME="TIMER2", TYPE=PCSR_CT2CS, ACCESS="R"),
        SEPARATOR(TEXTNAME=" LCDCE-"),
        FIELD[6](NAME="LCDCE", TYPE=PCSR_LCDCE, ACCESS="R"),
        SEPARATOR(TEXTNAME=" PMWCE-"),
        FIELD[7](NAME="PMWCE", TYPE=PCSR_PWMCE, ACCESS="R"),
        SEPARATOR(TEXTNAME=" SIFCE-"),
        FIELD[8](NAME="SIFCE", TYPE=PCSR_SIRCE, ACCESS="RW")    
}
</definition>   
</displaytype>

<displaytype>
  <name>UART0</name>
  <requires></requires>
  <definition>
TYPEDEF UART0_FREQ ENUM(WIDTH=9, DEFAULT="?")
{
                "OFF"           =   0,
                "XCLK"          =       1,
                "XCLK/2"        =       2,
                "XCLK/4"        =       4,
                "XCLK/8"        =       8,
                "XCLK/16"       =       16,
                "XCLK/32"       =       32,
                "XCLK/64"       =       64,
                "XCLK/128"      =       128,
                "XCLK/256"      =       256
}


TYPEDEF UART0(NAME="UART0", CLASS="Board") COMPOSITE(WIDTH=9)
{
        SEPARATOR(TEXTNAME="FREQ "),
        FIELD[8:0](NAME="UART0_FREQ", TYPE=UART0_FREQ, ACCESS="R")
}
</definition>   
</displaytype>

<displaytype>
  <name>UART1</name>
  <requires></requires>
  <definition>
TYPEDEF UART1_FREQ ENUM(WIDTH=9, DEFAULT="?")
{
                "OFF"           =   0,
                "XCLK"          =       1,
                "XCLK/2"        =       2,
                "XCLK/4"        =       4,
                "XCLK/8"        =       8,
                "XCLK/16"       =       16,
                "XCLK/32"       =       32,
                "XCLK/64"       =       64,
                "XCLK/128"      =       128,
                "XCLK/256"      =       256
}


TYPEDEF UART1(NAME="UART1", CLASS="Board") COMPOSITE(WIDTH=9)
{
        SEPARATOR(TEXTNAME="FREQ "),
        FIELD[8:0](NAME="UART1_FREQ", TYPE=UART1_FREQ, ACCESS="R")
}
</definition>   
</displaytype>

<displaytype>
        <name>UART_RSR</name>
        <definition>

TYPEDEF UART_RSR_ERROR ENUM(WIDTH=1, DEFAULT="?")
{
        "YES"           = 1,
        "NO"            = 0
}

TYPEDEF UART_RSR (NAME="UART_RSR", CLASS="Integrator") COMPOSITE(WIDTH=8)
{
        SEPARATOR(TEXTNAME="OE="),
        FIELD[3] (NAME="OE", TYPE=UART_RSR_ERROR, ACCESS="R"),
        SEPARATOR(TEXTNAME=" BE="),
        FIELD[2] (NAME="BE", TYPE=UART_RSR_ERROR, ACCESS="R"),
        SEPARATOR(TEXTNAME=" PE="),
        FIELD[1] (NAME="PE", TYPE=UART_RSR_ERROR, ACCESS="R"),
        SEPARATOR(TEXTNAME=" FE="),
        FIELD[0] (NAME="FE", TYPE=UART_RSR_ERROR, ACCESS="R")
}

        </definition> 
</displaytype>

<displaytype>
        <name>UART_LCRH</name>
        <definition>

TYPEDEF UART_LCRH_WLEN ENUM(WIDTH=2, DEFAULT="?")
{
        "8Bits"         = 3,
        "7Bits"         = 2,
        "6Bits"         = 1,
        "5Bits"         = 0
}

TYPEDEF UART_LCRH_ENA   ENUM(WIDTH=1, DEFAULT="?")
{
        "ENA"           = 1,
        "DIS"           = 0
}

TYPEDEF UART_LCRH_ODD   ENUM(WIDTH=1, DEFAULT="?")
{
        "ODD"           = 0,
        "EVEN"          = 1
}

TYPEDEF UART_LCRH (NAME="UART_LCRCH", CLASS="Integrator") COMPOSITE(WIDTH=8)
{
        SEPARATOR(TEXTNAME="WLEN="),
        FIELD[6:5] (NAME="WLEN", TYPE=UART_LCRH_WLEN, ACCESS="RW"),
        SEPARATOR(TEXTNAME=" FIFOS="),
        FIELD[4] (NAME="FEN", TYPE=UART_LCRH_ENA, ACCESS="RW"),
        SEPARATOR(TEXTNAME=" STP2="),
        FIELD[3] (NAME="STP2", TYPE=UART_LCRH_ENA, ACCESS="RW"),
        SEPARATOR(TEXTNAME=" PEN="),
        FIELD[1] (NAME="PARITYEN", TYPE=UART_LCRH_ENA, ACCESS="RW"),
        SEPARATOR(TEXTNAME=" EPS="),
        FIELD[2] (NAME="PARITY", TYPE=UART_LCRH_ODD, ACCESS="RW"),
        SEPARATOR(TEXTNAME=" BRK="),
        FIELD[0] (NAME="BREAK", TYPE=UART_LCRH_ENA, ACCESS="RW")
}
        
        </definition>
</displaytype>

<displaytype>
        <name>UART_FR</name>
        <definition>

TYPEDEF UART_FR_SET ENUM(WIDTH=1, DEFAULT="?")  
{
        "1"                     = 1,
        "0"                     = 0
}

TYPEDEF UART_FR_BUSY ENUM(WIDTH=1, DEFAULT="?")
{
        "BUSY"          = 1,
        "IDLE"          = 0
}

TYPEDEF UART_FR (NAME="UART_FR", CLASS="Integrator") COMPOSITE(WIDTH=8)
{
        SEPARATOR(TEXTNAME="TXFE="),
        FIELD[7] (NAME="TXFE", TYPE=UART_FR_SET, ACCESS="R"),
        SEPARATOR(TEXTNAME=" RXFF="),
        FIELD[6] (NAME="RXFF", TYPE=UART_FR_SET, ACCESS="R"),
        SEPARATOR(TEXTNAME=" TXFF="),
        FIELD[5] (NAME="TXFF", TYPE=UART_FR_SET, ACCESS="R"),
        SEPARATOR(TEXTNAME=" BUSY="),
        FIELD[3] (NAME="BUSY", TYPE=UART_FR_BUSY, ACCESS="R"),
        SEPARATOR(TEXTNAME=" DCD="),
        FIELD[2] (NAME="DCD", TYPE=UART_FR_SET, ACCESS="R"),
        SEPARATOR(TEXTNAME=" DSR="),
        FIELD[1] (NAME="DSR", TYPE=UART_FR_SET, ACCESS="R"),
        SEPARATOR(TEXTNAME=" CTS="),
        FIELD[0] (NAME="CTS", TYPE=UART_FR_SET, ACCESS="R")
}

        </definition>
</displaytype>

<displaytype>
        <name>UART_IIR</name>
        <definition>

TYPEDEF UART_IIR_SET ENUM(WIDTH=1, DEFAULT="?")
{
        "1"                     = 1,
        "0"                     = 0
}

TYPEDEF UART_IIR (NAME="UART_IIR", CLASS="Integrator") COMPOSITE(WIDTH=8)
{
        SEPARATOR(TEXTNAME="RTIS="),
        FIELD[3] (NAME="RTIS", TYPE=UART_IIR_SET, ACCESS="R"),
        SEPARATOR(TEXTNAME=" TIS="),
        FIELD[2] (NAME="TIS", TYPE=UART_IIR_SET, ACCESS="R"),
        SEPARATOR(TEXTNAME=" RIS="),
        FIELD[1] (NAME="RIS", TYPE=UART_IIR_SET, ACCESS="R"),
        SEPARATOR(TEXTNAME=" MIS="),
        FIELD[0] (NAME="MIS", TYPE=UART_IIR_SET, ACCESS="R")
}

        </definition>
</displaytype>

<displaytype>
        <name>UART_CR</name>
        <definition>

TYPEDEF UART_CR_LBE ENUM(WIDTH=1, DEFAULT="?")
{
        "0"                     = 0,
        "1"                     = 1
}

TYPEDEF UART_CR_ENA ENUM(WIDTH=1, DEFAULT="?")
{
        "ENA"           = 1,
        "DIS"           = 0
}

TYPEDEF UART_CR (NAME="UART_CR", CLASS="Integrator") COMPOSITE(WIDTH=8)
{
        SEPARATOR(TEXTNAME="UART="),
        FIELD[0] (NAME="UARTEN", TYPE=UART_CR_ENA, ACCESS="RW"),
        SEPARATOR(TEXTNAME=" LBE="),
        FIELD[7] (NAME="LBE", TYPE=UART_CR_LBE, ACCESS="RW"),
        SEPARATOR(TEXTNAME=" RTIE="),
        FIELD[6] (NAME="RTIE", TYPE=UART_CR_ENA, ACCESS="RW"),
        SEPARATOR(TEXTNAME=" TIE="),
        FIELD[5] (NAME="TIE", TYPE=UART_CR_ENA, ACCESS="RW"),
        SEPARATOR(TEXTNAME=" RIE="),
        FIELD[4] (NAME="RIE", TYPE=UART_CR_ENA, ACCESS="RW"),
        SEPARATOR(TEXTNAME=" MSIE="),
        FIELD[3] (NAME="MSIE", TYPE=UART_CR_ENA, ACCESS="RW")
}
        
        </definition>
</displaytype>


<displaytype>
        <name>KMI_CR</name>
        <definition>

TYPEDEF KMI_CR_TYPE ENUM(WIDTH=1, DEFAULT="?")
{
        "PS2/AT"        = 0,
        "None"          = 1
}

TYPEDEF KMI_CR_EIN ENUM(WIDTH=1, DEFAULT="?")
{
        "ENA"           = 1,
        "DIS"           = 0
}

TYPEDEF KMI_CR_FK ENUM(WIDTH=1, DEFAULT="?")
{
        "SET"           = 1,
        "NOT SET"       = 0
}

TYPEDEF KMI_CR (NAME="KMI_CRI", CLASS="Integrator") COMPOSITE(WIDTH=8)
{
        SEPARATOR(TEXTNAME="Type="),
        FIELD[5] (NAME="TYPE", TYPE=KMI_CR_TYPE, ACCESS="RW")
        SEPARATOR(TEXTNAME=" REIN="),
        FIELD[4] (NAME="RIEN", TYPE=KMI_CR_EIN, ACCESS="RW"),
        SEPARATOR(TEXTNAME=" TIEN="),
        FIELD[3] (NAME="TIEN", TYPE=KMI_CR_EIN, ACCESS="RW"),
        SEPARATOR(TEXTNAME=" KMIEN"),
        FIELD[2] (NAME="KMEIN", TYPE=KMI_CR_EIN, ACCESS="RW"),
        SEPARATOR(TEXTNAME=" FKMID="),
        FIELD[1] (NAME="FKMID", TYPE=KMI_CR_FK, ACCESS="RW"),
        SEPARATOR(TEXTNAME=" FKMIC="),
        FIELD[0] (NAME="FKMIC", TYPE=KMI_CR_FK, ACCESS="RW")
}

        </definition>
</displaytype>

<displaytype>
        <name>KMI_STAT</name>
        <definition>

TYPEDEF KMI_STAT_EMPTY ENUM(WIDTH=1, DEFAULT="?")
{
